services:
  conduit:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8888
  postgres:
    image: postgres:16.2
    container_name: conduit_postgres
    environment:
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
      POSTGRES_PORT: 15432
